# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce5d45ad1f4ec9ec25450284e6fdf8277d241aefbc424a72d16b2b75cffbc29ac97a543a9d0c0bd4df16aab429514d2bff2784650f57f8f818fc2530dcf12cfb

test:
  secret_key_base: 6c9546a42f4297b22c62522f49c8ccd73133e22b6cfbe51940aaa4bb3ff51aeae378130599d23f6dd0869dec8647543e54306d4eb4f8eafab529a802dee1465f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
